implement logic with categoriies
Nikitos787/book-store pull request #10
Opened 2023-08-27 20:19 UTC by Nikitos787

2023-08-29 13:23 UTC, yevheniisynytsia requested changes
I will get a clear understanding of how the mapper should work and we'll come back to it later. For now, that's all the comments I have. Good job! Keep Up the Good Work!

2023-08-29 13:23 UTC, yevheniisynytsia commented on src/main/java/project/bookstore/controller/BookController.java
> +    @Operation(summary = "Add category to book from db")
```suggestion
    @Operation(summary = "Remove category from db")
```

2023-08-29 13:23 UTC, yevheniisynytsia commented on src/main/java/project/bookstore/controller/CategoryController.java
> +    @PreAuthorize("hasAuthority('ROLE_ADMIN')")
as for me, it makes the code a bit messy. 
`@Secured` annotation makes almost the same, but without `hasAuthority` part. https://www.baeldung.com/spring-security-method-security#:~:text=3.-,Applying,-Method%20Security

Also, I would move literals like `ROLE_ADMIN`, `ROLE_USER` to some constant/enum to reuse code, but not literals where you can easily missclick while writing and have bugs

2023-08-29 13:23 UTC, yevheniisynytsia commented on src/main/java/project/bookstore/controller/CategoryController.java
> +    @PreAuthorize("hasAnyAuthority('ROLE_ADMIN', 'ROLE_USER')")
fancy tip: write mapping annotation first to easily understand what HTTP method this method works with

2023-08-29 13:23 UTC, yevheniisynytsia commented on src/main/java/project/bookstore/repository/CategoryRepository.java
> +@Repository
`@Repository` is not required, but it's ok with it too. 
Just to be sure and mark it as a repository

2023-08-29 13:23 UTC, yevheniisynytsia commented on src/main/java/project/bookstore/repository/book/BookRepository.java
> +    @Query("FROM Book b LEFT JOIN FETCH b.categories WHERE b.id =:id")
```suggestion
    @Query("FROM Book b LEFT JOIN FETCH b.categories WHERE b.id = :id")
```

2023-08-29 13:23 UTC, yevheniisynytsia commented on src/main/java/project/bookstore/repository/book/specification/AuthorSpecificationProvider.java
> +    private static final String JOIN_TABLE = "categories";
`JOIN_TABLE` is not a meaningful name for a variable. Let's name it `CATEGORIES_TABLE` so that you read the code and understand what table you are joining without reading the variable value

2023-09-11 10:40 UTC, Andriy-dz approved these changes

2023-09-14 11:04 UTC, Andriy-dz approved these changes

2023-09-20 11:19 UTC, merged