implement shopping cart
Nikitos787/book-store pull request #11
Opened 2023-08-30 13:02 UTC by Nikitos787

2023-08-31 14:03 UTC, yevheniisynytsia requested changes
In general, looks good! Some comments to go

2023-08-31 14:03 UTC, yevheniisynytsia commented on src/main/java/project/bookstore/model/ShoppingCart.java
> +    @Id
@GeneratedValue(strategy = GenerationType.IDENTITY)

2023-08-31 14:03 UTC, yevheniisynytsia commented on src/main/java/project/bookstore/service/CartItemService.java
> +public interface CartItemService {
do we need this service?

2023-08-31 14:03 UTC, yevheniisynytsia commented on src/main/java/project/bookstore/service/ShoppingCartService.java
> +    ShoppingCart save(User user);
user is probably too much, let's pass userId to the methods

2023-08-31 14:03 UTC, yevheniisynytsia commented on src/main/java/project/bookstore/service/impl/CartItemServiceImpl.java
> +public class CartItemServiceImpl implements CartItemService {
I suppose we can move some of this logic to ShoppingCartServiceImpl and use CartItemRepository there

2023-09-14 11:17 UTC, Andriy-dz approved these changes

2023-09-14 11:17 UTC, Andriy-dz commented on src/main/java/project/bookstore/mapper/CartItemMapper.java
> +    CartItem toModel(CartItemRequestDto cartItemRequestDto);
It may be helpful to add @Named("bookFromId") default Book bookFromId(Long id) { // your implementation here} to the BookMapper interface

2023-09-20 11:05 UTC, Andriy-dz approved these changes

2023-09-20 11:06 UTC, Andriy-dz approved these changes

2023-09-20 11:19 UTC, merged