implement security to project
Nikitos787/book-store pull request #7
Opened 2023-08-25 12:15 UTC by Nikitos787

2023-08-28 10:19 UTC, Andriy-dz requested changes
Good Job! Let's improve your solution!

2023-08-28 10:19 UTC, Andriy-dz commented on src/main/java/project/bookstore/controller/AuthenticationController.java
> +    private final PasswordEncoder passwordEncoder;
field that is not used

2023-08-28 10:19 UTC, Andriy-dz commented on src/main/java/project/bookstore/config/ApplicationConfiguration.java
> +    public UserDetailsService userDetailsService() {
it is better to make your own implementation instead of a bean for UserDetailsService

2023-08-28 10:19 UTC, Andriy-dz commented on src/main/java/project/bookstore/repository/RoleRepository.java
> +@Repository
you can do without this annotation

2023-08-28 10:19 UTC, Andriy-dz commented on src/main/java/project/bookstore/repository/UserRepository.java
> +@Repository
same

2023-08-28 10:19 UTC, Andriy-dz commented on src/main/resources/application.properties
> +
regular empty lines

2023-08-28 10:19 UTC, Andriy-dz commented on src/main/resources/db/changelog/changes/05-insert-roles-to-db.yaml
> +
and these files should not have an empty line at the end

2023-08-28 10:20 UTC, Andriy-dz requested changes
s

2023-08-31 10:04 UTC, yevheniisynytsia approved these changes
LGTM!

2023-09-04 14:58 UTC, merged